[libraries]
assertJ             = { module = "org.assertj:assertj-core", version = "3.27.6" }
unit                = { module = "org.junit.jupiter:junit-jupiter", version = "6.0.1" }
unitPlatform        = { module = "org.junit.platform:junit-platform-runner", version = "1.14.1" }

[bundles]
testUnit            = [ "assertJ", "unit", "unitPlatform" ]
